import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import {NextUIProvider} from "@nextui-org/react";
import Footer from "@/components/footer";
import {SessionProvider} from "next-auth/react";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Rrenavirk",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <NextUIProvider>
            <SessionProvider>
            <Navbar/>
            {children}
            <Footer/>
            </SessionProvider>
        </NextUIProvider>
        </body>
        </html>
    );
}
